version: 1
formatters:
  simple:
    format: "%(asctime)s\t%(name)s\t%(levelname)s\t%(pathname)s:%(lineno)s\n%(message)s\n"
  minimal:
    format: '%(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
  full:
    class: logging.FileHandler
    level: INFO
    formatter: simple
    filename: wes.log
  cmd:
    class: logging.FileHandler
    level: INFO
    filename: cmd.log
    formatter: minimal
  ptime:
    class: logging.FileHandler
    level: INFO
    filename: time.log
    formatter: minimal
loggers:
  cmd:
    level: DEBUG
    handlers: [cmd]
    propagate: no
  ptime:
    level: DEBUG
    handlers: [ptime]
    propagate: no
root:
  level: DEBUG
  handlers: [console, full]
